### ISSUE TITLE
PRACTICA #9 BASE DE DATOS 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-m-a-r-topicos-a-p#1]
[PRACTICA #9 VISUAL.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-m-a-r-topicos-a-p/files/8713134/PRACTICA.9.VISUAL.pdf)
[basedatos1.zip](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipo-m-a-r-topicos-a-p/files/8713161/basedatos1.zip)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
